// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SchedulerWebApi.Models;
using System;

namespace SchedulerWebApi.Migrations.UserAppointment
{
    [DbContext(typeof(UserAppointmentContext))]
    [Migration("20180523023408_CreateUserAppointmentModel")]
    partial class CreateUserAppointmentModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("SchedulerWebApi.Models.UserAppointment", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("AppointmentId");

                    b.HasKey("UserId", "AppointmentId");

                    b.ToTable("UserAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
